### ISSUE TITLE
No way to check the value of a word by string?

### ISSUE THREAD

**Issue by Mxdi** [IonicaBizau/count-words#13]
So im trying to use this module which is VERY basic. I am trying to check how many times a certain word was counted for. However I cant use any variable such as: "string" because it looks for what ever string is attached to the wordcounter.... So if I did:

var finder = countWords(words);

console.log(finder.string); (String is defined before its called for)

It doesn't check for MY string. It checks for the literal word "String". Would enjoy a fix for this VERY much. - Medi.

**Comment by IonicaBizau** [comment]
Can you please provide the exact code you work with?
